services:
  fe-app:
    image: belshed/fe-app
    pull_policy: 'always'
    hostname: fe-app
    ports:
      - 81:3000
  # dockerhub-fetcher:
  #   image: belshed/dockerhub-fetcher
  #   pull_policy: 'always'
  #   hostname: dockerhub-fetcher
  #   ports:
  #     - 82:3333
  webhook:
    image: almir/webhook
    pull_policy: 'always'
    hostname: webhook
    ports:
      - 9000:9000
    volumes:
      /home/sergdenisov/webhooks:/etc/webhook
    command: -verbose -hooks=/etc/webhook/hooks.json -hotreload
  nginx:
    image: belshed/nginx
    pull_policy: 'always'
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/ssl/private
    depends_on:
     - fe-app
     - webhook
