services:
  fe-app:
    image: belshed/fe-app
    hostname: fe-app
    ports:
      - 81:3000
  dockerhub-fetcher:
    image: belshed/dockerhub-fetcher
    hostname: dockerhub-fetcher
    ports:
      - 82:3333
  nginx:
    image: belshed/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/sergdenisov/certs:/etc/ssl/private
    depends_on:
     - fe-app