services:
  fe-app:
    image: belshed/fe-app
    pull_policy: 'always'
    container_name: volokut-fe-app
    hostname: volokut-fe-app
    networks:
      - gateway-network
    entrypoint: node .output/server/index.mjs

networks:
  gateway-network:
    external: true
    name: gateway-network